apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-restore
spec:
  storageClassName: csi-cephfs-sc
  dataSource:
    name: new-snapshot-cephfs
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
