apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-cephfs
spec:
  volumeSnapshotClassName: csi-cephfs-snapclass
  source:
    # REPLACE THIS VALUE
    persistentVolumeClaimName: csi-cephfs-pvc
