apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    volumeDevices:
      - name: pvc
        devicePath: /dev/data
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: rbd-pvc
