apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-rbd
spec:
  volumeSnapshotClassName: csi-rbd-snapclass
  source:
    # REPLACE THIS VALUE
    persistentVolumeClaimName: rbd-pvc
