# permissions for end users to edit cephblockpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephblockpool-editor-role
rules:
- apiGroups:
  - hypersds.tmax.io
  resources:
  - cephblockpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hypersds.tmax.io
  resources:
  - cephblockpools/status
  verbs:
  - get
