# permissions for end users to view cephclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephcluster-viewer-role
rules:
- apiGroups:
  - hypersds.tmax.io
  resources:
  - cephclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypersds.tmax.io
  resources:
  - cephclusters/status
  verbs:
  - get
