# permissions for end users to view cephblockpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephblockpool-viewer-role
rules:
- apiGroups:
  - hypersds.tmax.io
  resources:
  - cephblockpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypersds.tmax.io
  resources:
  - cephblockpools/status
  verbs:
  - get
