apiVersion: hypersds.tmax.io/v1alpha1
kind: CephCluster
metadata:
  name: cephcluster-sample
spec:
  mon:
    count: 1
  osd:
    - hostName: centos-node4
      devices:
        - /dev/sdb
  nodes:
    - ip: 192.168.33.21
      # userId SHOULD BE ROOT
      userId: root
      password: "ck@3434"
      hostName: centos-node4
