apiVersion: hypersds.tmax.io/v1alpha1
kind: CephCluster
metadata:
  name: cephcluster-sample
spec:
  mon:
    count: 1
  nodes:
    - name: vagrant
      accessInfo:
        ip: 192.168.33.31
        userId: tmax
        password: "ck@3434"
        hostName: vagrant
      devices:
        - /dev/sdb
