---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  # Users do not need to modify unless static provisioning is required
  userID: mds.myfs.s1-2.esxjmt
  userKey: AQAM2RhgnFjEERAAJIqs01FlgRqm2eEuBnEGHQ==

  # Required for dynamically provisioned volumes
  adminID: admin
  # REPLACE THIS VALUE
  adminKey: AQCeBcZftAEvExAAultsKBpNpiWWGi06Md7mmw==
