// Code generated by MockGen. DO NOT EDIT.
// Source: ssh_wrapper.go

// Package wrapper is a generated GoMock package.
package wrapper

import (
	bytes "bytes"
	gomock "github.com/golang/mock/gomock"
	ssh "golang.org/x/crypto/ssh"
	reflect "reflect"
)

// MockSSHInterface is a mock of SSHInterface interface
type MockSSHInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSSHInterfaceMockRecorder
}

// MockSSHInterfaceMockRecorder is the mock recorder for MockSSHInterface
type MockSSHInterfaceMockRecorder struct {
	mock *MockSSHInterface
}

// NewMockSSHInterface creates a new mock instance
func NewMockSSHInterface(ctrl *gomock.Controller) *MockSSHInterface {
	mock := &MockSSHInterface{ctrl: ctrl}
	mock.recorder = &MockSSHInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSSHInterface) EXPECT() *MockSSHInterfaceMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockSSHInterface) Run(addr, command string, resultStdout, resultStderr *bytes.Buffer, config *ssh.ClientConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", addr, command, resultStdout, resultStderr, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockSSHInterfaceMockRecorder) Run(addr, command, resultStdout, resultStderr, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSSHInterface)(nil).Run), addr, command, resultStdout, resultStderr, config)
}
