name: hypersds-operator
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  release:
    types:
      - published
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
  static-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: static test
        run: make static-test
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install kubebuilder
        run: make kubebuilder-download
      - name: unit test
        run: make unit-test
  image-build:
    needs: [lint, static-test, unit-test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install kubebuilder
        run: make kubebuilder-download
      - name: build
        run: make docker-build
  e2e:
    needs: [image-build]
    runs-on: self-hosted
    timeout-minutes: 40
    strategy:
      matrix:
        config:
        - {k8s: v1.19.8, runtime: crio, network: calico}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: |
          export KUBE_VERSION=${{ matrix.config.k8s }} KUBE_RUNTIME=${{ matrix.config.runtime }} KUBE_NETWORK=${{ matrix.config.network }}
          ./hack/cluster.sh up
          docker login -u=tmaxanc+robot -p=${{ secrets.QUAY_PASSWORD }} quay.io
          make e2e
  cleanup:
    needs: [e2e]
    runs-on: self-hosted
    steps:
      - run: ./hack/cluster.sh down


