name: assign-automation
on: 
  pull_request:
    types: [opened, ready_for_review, edited]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: reviewers
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: hyoung-90, hbinkim
          max-num-of-reviewers: 2
          draft-keyword: wip

